- hosts: localhost
  gather_facts: false
  vars_files:
  - mysecrets
  - myvars

  tasks:
  - name: Try to login to OCP cluster
    k8s_auth:
      host: "{{ ocp_master }}"
      username: opentlc-mgr
      password: "{{ ocp_password }}"
      validate_certs: no
    register: k8s_auth_result
    
  - name: Create a Deployment by reading the definition from a local file
    k8s:
      namespace: testing
      state: present
      src: ~/ansible/hello-openshift.yml
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
