- hosts: localhost
  gather_facts: false
  vars_files:
  - mysecrets
  - myvars
  
  tasks:
  - name: Try to login to OCP cluster
    k8s_auth:
      host: "{{ ocp_master }}"
      username: opentlc-mgr
      password: "{{ ocp_password }}"
      validate_certs: no
    register: k8s_auth_result

  - name: Get a list of all pods from testing
    k8s_info:
      namespace: testing
      api_key: "{{ k8s_auth_result.k8s_auth.api_key }}"
      kind: Pod
    register: pod_list

  - name: Print pod list
    debug:
      msg: "pod_list: {{ pod_list | json_query('resources[*].metadata.name')  }}"
